### ISSUE TITLE
@oscarmcm: Will not execute command in 0.6.1

### ISSUE THREAD

**Issue by jrappen** [aziz/DistractionFreeWindow#17]
## Bug report from @oscarmcm:

@jrappen I just tried v0.6.1 and the keyboard shortcut does not execute the command

Default (OSX).sublime-keymap - User

```json
[ { "keys": ["super+shift+f11"], "command": "distraction_free_window" } ]
```

**Comment by jrappen** [comment]
@oscarmcm

I cannot reproduce this as I'm not on OSX, changing the default keyboard shortcut to something else on Windows works as expected.

Could you check the console when trying your shortcut after having enabled `import sublime; sublime.log_commands(True)` there?

**Comment by jrappen** [comment]
## From @oscarmcm:

Hey @jrappen there is the stack trace

```python
Traceback (most recent call last):
  File "sublime_plugin.py", line 553, in run_
    return self.run()
  File "distraction_free_window in DistractionFreeWindow.sublime-package", line 29, in run
  File "distraction_free_window in DistractionFreeWindow.sublime-package", line 192, in is_menu_visible
AttributeError: 'Window' object has no attribute 'is_menu_visible'
```

**Comment by jrappen** [comment]
@oscarmcm: Package Control should be updating DistractionFreeWindow to `0.6.2` in about an hour.
