### ISSUE TITLE
SyntaxError: invalid syntax on `Sublime Text` start

### ISSUE THREAD

**Issue by evandrocoan** [aziz/DistractionFreeWindow#20]
#### A summary of the issue

After install this plugin, close sublime and open it, this pops up on the console:

```
reloading plugin DictionaryAutoComplete.DictionaryAutoComplete
reloading plugin DistractionFreeWindow.distraction_free_window
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 658, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "distraction_free_window in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\DistractionFreeWindow.sublime-package", line 29
    if sublime.platform() not "osx":
                                  ^
SyntaxError: invalid syntax
reloading plugin Emmet.emmet-plugin
```

### Environment

```text
DistractionFreeWindow:
    release:        0.6.3

Sublime Text:
    channel:        stable
    version:        Build 3114 (portable)
    platform:       Windows
    architecture:   x64
```

**Comment by jrappen** [comment]
Should be fixed in `v0.6.4`, sorry about that. Please give Package Control an hour to update the package.
